
database:
  connection:
    jdbc:
      driver: 'oracle.jdbc.driver.OracleDriver'
      url: 'jdbc:oracle:thin:@fei-sql3.upceucebny.cz:1521:BDAS'
      username: 'st64512'
      password: 'abcde'
server:
  port: 8080
